### PR TITLE
Fix hljs button

### LINKED ISSUE #11: Fix hljs button
Currently code buttons (playpen + clipboard) are not very pretty, the goal is to have something as clean as mdBook.

### PR DESCRIPTION
**Pull request by lunchboxav**
This fixes https://github.com/oknozor/unveil-rs/issues/11. I made the button smaller, tone down the black color a little bit and put them on top right of the code box. 

Screenshot:
Screen Shot 2020-03-22 at 7 08 22 PM

### CODE REVIEW

**Comment by oknozor** [comment]
Hey @lunchboxav, this is super nice ! I just need to fix the build before we can merge this. Also it would be nice to avoid merge commit. I'll let you know when the build is fixed (I am having hard time with this) so you can rebase and merge.

**Comment by lunchboxav** [comment]
Ah sorry for that @oknozor. I should’ve rebase. Will do that after you solved the build issue. I hope everything runs smooth :D

**Comment by oknozor** [comment]
I am done with the build, from now on I will not force push ever again I promise. You can rebase on current mater so I can merge this.

**Comment by oknozor** [comment]
@lunchboxav did you manage to rebase ? If not I did it on https://github.com/oknozor/unveil-rs/tree/lunchboxav/hljs-button. I must admit it was a bit of a mess :smile: 
Also, I just saw you committed your personal demo file. Please remove it from the commit it's about 10 000 lines of duplication.

**Comment by lunchboxav** [comment]
Oh no, my bad, sorry. I thought I've had that double-checked. I've actually rebased this branch which lives in my fork. However, I'll check the branch that you've created. If that's okay, I'll create a new PR based on that branch and close this one. Sounds good? Terribly sorry about this.

**Comment by oknozor** [comment]
No problem, it's fine :)

**Comment by lunchboxav** [comment]
@oknozor I'm closing this PR and supersede this with https://github.com/oknozor/unveil-rs/pull/23, as the commit message and files are cleaner. Is that okay?

**Comment by oknozor** [comment]
Merged in #23

**Pull request closed without merging**
