### PR TITLE
Implementing Animated Transition

### PR DESCRIPTION
**Pull request by lunchboxav**
This PR partially addresses #4. I'm implementing zoom in/out and fade in/out animation as a transition between slides. I haven't implemented setting up this transition via stylematter yet , so right now, to test it, we have to manually change the `assets/unveil.js`.

This is a pretty naive implementation, so, I'm always open for discussions and feedback :D

### CODE REVIEW

**Comment by oknozor** [comment]
Thank you @lunchboxav I'll be taking a look at your PR at noon (EU). I am working right now. can you rebase the master branch to resolve conflicts ? Also we probably need to follow a better branching model if people are going to contribute to unveil.

**Comment by oknozor** [comment]
Sorry I did not tell you before but The project will be following the [conventional commit](https://www.conventionalcommits.org/en/v1.0.0/) spec to generate change logs. If you don't mind renaming your commit messages to match the spec.

**Comment by lunchboxav** [comment]
ah, my bad. Ok, so, is `feat: added CSS animation for slide transition` a valid commit message? Sorry, but I've never used conventional commit, so I need to verify this.

Also, I should squash all my commits into one commit, right? cmiiw.

In terms of branching, normally I do one branch per issue, but I agree that we may need to address this convention as well. Would love to discuss and have some agreement on this as well.

**Comment by oknozor** [comment]
Your commit message is good, and squashing would be appreciated. I will create a matrix channel asap so we can discuss this.

**Comment by lunchboxav** [comment]
That sounds very awesome @oknozor :D

**Comment by oknozor** [comment]
Hello, @lunchboxav, I took the liberty to implement this slightly differently so the end user can quickly add predefined transitions and also add its own.   

To add a transition to a slide we now use the following css custom property : 
```
+++
--on-enter-animation: fade-in
+++
```

The custom property is checked at runtime on the javascript side like this : 
```javascript
    let transition_kind = getComputedStyle(target_slide).getPropertyValue("--on-enter-animation").trim();
```

We only define an "on enter" behavior, because `scrollIntoView({behavior: "smooth"})` behavior/timing conflicts with the animation previously triggered on the starting slide (ie. `starting_slide -> animation -> scroll -> animation -> target_slide`). In my opinion, it feels much simpler to just define one animation per slide which is trigger either entering from right to left or from left to right. 

Your current implementation conflict with this, that's why I am closing your PR. I am sorry I am not merging this, but in fact your code helped me a lot to figure out the current implementation.   

Also you are very welcome to add more transition if you want to. This can now be done only editing [unveil.css](src/assets/unveil.css).

If you want to chat, I have created a matrix room [here](https://riot.im/app/#/room/#unveil-rs:matrix.org).

**Pull request closed without merging**
